name: pdfeditorapp
description:
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  curved_navigation_bar:
  url_launcher:
  file_picker: ^11.0.2
  syncfusion_flutter_pdfviewer:
  syncfusion_flutter_pdf:
  pdftron_flutter:
  pdf:
  path_provider:
  open_file:
  http:
  path:
  share_plus:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


flutter:

  assets:
    - assets/images/

  uses-material-design: true
